versions:
  schema: 1.0
  rejigger: 0.0.1
  template: 1.0
template:
  args:
    - name: project_name
      description: Name of the source code project
    - name: description
      description: short summary of the new project
    - name: author
      description: Name of the person who owns the new project
    - name: version
      description: Initial version number for the project